### ISSUE TITLE
Can't get the bundle to show up under the agent section.

### ISSUE THREAD

**Issue by ghost** [defract/Colima.bundle#1]
I've installed according to the instructions and can't get Colima to show up under Agent when in the advanced section. I've tried both the downloaded zip file as is and tried to rename it to Colima.bundle but neither work. Am I doing something wrong here? 

Running the latest version of Plex Media Server on a mac with Catalina.

**Comment by defract** [comment]
Hello, maybe post a picture of what it currently looks like? Incorrect naming is usually the #1 issue why it is not working.

**Comment by ghost** [comment]
[Here's a link to my screenshots.](https://imgur.com/a/JwIOCmU) I restarted Plex Media Server after installing the bundle too and still no luck. Any help would be amazing!

**Comment by defract** [comment]
Sorry, that it is going rather slow.

I just noticed (I don't have a Mac), it seems you renamed the downloaded Zip to bundle? You need to unpack it. The folder structure will look like "Plex Media Server\Plug-ins\Colima.bundle\Contents\" then.

**Comment by defract** [comment]
> [Here's a link to my screenshots.](https://imgur.com/a/JwIOCmU) I restarted Plex Media Server after installing the bundle too and still no luck. Any help would be amazing!

And, did my answer help you?

**Comment by ghost** [comment]
> And, did my answer help you?

Sorry for the delayed reply. That seems to have done the trick, I swear I tried it this way once before but I guess not.

**Comment by defract** [comment]
Thanks for getting back with an answer :).
